name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Upload release asset
        uses: actions/upload-artifact@v3
        with:
          path: target/release/mutiny-data-recovery
          name: mutiny-data-recovery_amd64

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Upload release asset
        uses: actions/upload-artifact@v3
        with:
          path: target/release/mutiny-data-recovery.exe
          name: mutiny-data-recovery.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release

      - name: Upload release asset
        uses: actions/upload-artifact@v3
        with:
          path: target/release/mutiny-data-recovery
          name: mutiny-data-recovery_darwin
